#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Zampher
# SPDX-License-Identifier: MPL-2.0

"""
Test script to verify that MinerU results are reused in Convert stage after Extract stage.
"""

import io
import os
import sys
import tempfile
import zipfile
from pathlib import Path

# Add the backend directory to Python path
sys.path.append(str(Path(__file__).parent))

from ir.document import Document
from ir.attachment_manager import AttachMentManager
from workflow.md_based_workflow import MarkdownBasedWorkflow, MarkdownBasedWorkflowConfig
from converter.x2md.converter_mineru import ConverterMineru, ConverterMineruConfig
from utils.markdown_utils import embed_inline_image_from_zip

# Mock configuration for testing
class MockLogger:
    def debug(self, msg):
        print(f"DEBUG: {msg}")
    def info(self, msg):
        print(f"INFO: {msg}")
    def warning(self, msg):
        print(f"WARNING: {msg}")
    def error(self, msg):
        print(f"ERROR: {msg}")

def create_test_pdf():
    """Create a simple test PDF file"""
    from reportlab.pdfgen import canvas
    
    temp_pdf = tempfile.NamedTemporaryFile(suffix=".pdf", delete=False)
    c = canvas.Canvas(temp_pdf.name)
    c.drawString(100, 750, "Hello, World!")
    c.drawString(100, 700, "This is a test PDF for MinerU reuse.")
    c.save()
    
    return temp_pdf.name

def create_mock_mineru_zip(markdown_content="# Test Document\n\nThis is a test document generated by MinerU.\n\n![Test Image](images/test.png)\n"):
    """Create a mock MinerU ZIP file with Markdown content"""
    buffer = io.BytesIO()
    
    with zipfile.ZipFile(buffer, 'w') as zf:
        # Add Markdown file
        zf.writestr('full.md', markdown_content)
        
        # Add a sample image
        sample_image = io.BytesIO()
        from PIL import Image, ImageDraw
        img = Image.new('RGB', (100, 100), color='red')
        draw = ImageDraw.Draw(img)
        draw.text((10, 50), "Test Image", fill='white')
        img.save(sample_image, format='PNG')
        sample_image.seek(0)
        
        zf.writestr('images/test.png', sample_image.read())
    
    buffer.seek(0)
    return buffer

def test_mineru_result_reuse():
    """Test that MinerU results are reused in Convert stage"""
    print("=== Testing MinerU Result Reuse ===")
    
    # Create test PDF
    test_pdf_path = create_test_pdf()
    try:
        # Read the PDF as a Document
        pdf_doc = Document.from_path(test_pdf_path)
        
        # Create mock MinerU ZIP bytes with sample content
        mock_zip_buffer = create_mock_mineru_zip("# Sample Content\n\nHello from MinerU!")
        mock_zip_bytes = mock_zip_buffer.read()
        
        # Create workflow config with all required parameters and skip_cache=True (simulating Convert stage)
        from converter.x2md.base import X2MarkdownConverterConfig
        from converter.x2md.converter_mineru import ConverterMineruConfig
        from translator.ai_translator.md_translator import MDTranslatorConfig
        from exporter.md.md2html_exporter import MD2HTMLExporterConfig
        
        # Create converter config
        converter_config = ConverterMineruConfig(
            mineru_token="dummy_token",
            formula_ocr=True
        )
        
        # Create translator config (minimal)
        translator_config = MDTranslatorConfig(
            base_url="https://api.example.com/v1",
            model_id="gpt-3.5-turbo",
            api_key="test_key",
            to_lang="zh",
            skip_translate=True  # Skip translation for testing purposes
        )
        
        # Create HTML exporter config
        html_exporter_config = MD2HTMLExporterConfig()
        
        workflow_config = MarkdownBasedWorkflowConfig(
            logger=MockLogger(),
            skip_cache=True,
            convert_engine="mineru",
            converter_config=converter_config,
            translator_config=translator_config,
            html_exporter_config=html_exporter_config
        )
        
        # Create workflow with config
        workflow = MarkdownBasedWorkflow(config=workflow_config)
        
        # Load the document
        workflow.read_bytes(
            content=pdf_doc.content,
            stem=pdf_doc.name,
            suffix=pdf_doc.suffix
        )
        
        # Directly set _layout_source_zip to simulate a previous MinerU result
        workflow._layout_source_zip = mock_zip_bytes
        
        # Test getting document markdown - this should reuse the MinerU result without API call
        try:
            import unittest.mock
            from workflow.md_based_workflow import MarkdownDocument
            
            # Mock the converter factory to avoid actual API calls
            with unittest.mock.patch.object(workflow, '_converter_factory', {'mineru': (None, None)}):
                # This should reuse the existing _layout_source_zip instead of calling MinerU API
                md_content = workflow._get_document_md(
                    convert_engine="mineru",
                    convert_config=converter_config
                )
                
                print("✅ SUCCESS: Markdown content generated without re-uploading to MinerU!")
                print(f"   Markdown content length: {len(md_content.content)}")
                print(f"   Markdown content preview: {md_content.content[:100]}...")
                
                return True
        except Exception as e:
            print(f"❌ ERROR: Failed to generate Markdown: {e}")
            import traceback
            traceback.print_exc()
            return False
    finally:
        # Clean up
        if os.path.exists(test_pdf_path):
            os.unlink(test_pdf_path)

if __name__ == "__main__":
    success = test_mineru_result_reuse()
    sys.exit(0 if success else 1)