# SPDX-FileCopyrightText: 2026 Zampher
# SPDX-License-Identifier: MPL-2.0

"""
Table processing utilities for PDF rendering.

This module provides shared table processing logic that can be used
by all PDF renderer implementations (ReportLab, HTML-to-PDF, etc.).
"""

from typing import List, Tuple, Optional, Callable
from html.parser import HTMLParser


class TableUtils:
    """
    Table processing utilities.
    
    Provides methods for parsing markdown tables, HTML tables,
    and calculating table column widths.
    """
    
    @staticmethod
    def parse_markdown_table(text: str) -> List[List[str]]:
        """
        Parse a simple markdown-style table (generated by LayoutMarkdownBuilder)
        into a 2D list of cell texts.
        
        Also checks for tab-separated values (TSV) format if tabs are present.

        Example:
            | A | B |
            |---|---|
            | 1 | 2 |
        
        Or tab-separated:
            A\tB
            1\t2
            
        Args:
            text: Markdown table or TSV text
            
        Returns:
            2D list of cell texts (rows x columns)
        """
        if not text or not text.strip():
            return []
        
        # Check if text contains tab characters (TSV format)
        if '\t' in text:
            rows = []
            lines = text.strip().split('\n')
            for line in lines:
                line = line.strip()
                if not line:
                    continue
                # Split by tab
                cells = [cell.strip() for cell in line.split('\t')]
                if cells:
                    rows.append(cells)
            if rows:
                return rows
        
        # Otherwise, parse as markdown table
        rows: List[List[str]] = []
        for line in text.splitlines():
            line = line.strip()
            if not line.startswith("|") or line.count("|") < 2:
                continue
            # Skip separator line like |---|---|
            stripped = line.strip("|").strip()
            if stripped and all(ch in "-: " for ch in stripped):
                continue
            parts = [cell.strip().replace("\\|", "|") for cell in line.split("|")[1:-1]]
            if parts:
                rows.append(parts)
        return rows
    
    @staticmethod
    def parse_html_table(html_str: str, log_warning: Optional[Callable[[str, Exception], None]] = None) -> Tuple[List[List[str]], List[Tuple[int, int, int, int]]]:
        """
        Parse HTML table string directly into a 2D list of cell texts and span information.
        
        This handles rowspan and colspan attributes and returns both the cell data
        and the span commands needed for ReportLab Table.
        
        Args:
            html_str: HTML table string (e.g., "<table><tr><td rowspan=\"2\">...</td></tr></table>")
            log_warning: Optional callback function for logging warnings (msg: str, error: Exception)
            
        Returns:
            Tuple of:
            - 2D list of cell texts: [[row1_col1, row1_col2, ...], [row2_col1, ...], ...]
            - List of span commands: [(row_start, col_start, row_end, col_end), ...]
              where (row_start, col_start) is the top-left cell and (row_end, col_end) is bottom-right
        """
        class HTMLTableParser(HTMLParser):
            def __init__(self):
                super().__init__()
                self.rows: List[List[str]] = []
                self.spans: List[Tuple[int, int, int, int]] = []  # (row_start, col_start, row_end, col_end)
                self.current_row: List[str] = []
                self.current_row_index = -1
                self.current_col_index = 0
                self.in_cell = False
                self.current_cell_parts: List[str] = []
                self.current_cell_rowspan = 1
                self.current_cell_colspan = 1
                self.in_table = False
                self.pending_rowspans: dict = {}  # col_index -> remaining_rows
                
            def handle_starttag(self, tag, attrs):
                if tag == "table":
                    self.in_table = True
                    self.current_row_index = -1
                elif tag == "tr" and self.in_table:
                    self.current_row = []
                    self.current_row_index += 1
                    self.current_col_index = 0
                    # Handle pending rowspans: add empty cells where rowspan continues
                    for col_idx in sorted(self.pending_rowspans.keys()):
                        if self.pending_rowspans[col_idx] > 0:
                            self.current_row.append("")  # Placeholder for rowspan continuation
                            self.pending_rowspans[col_idx] -= 1
                            if self.pending_rowspans[col_idx] == 0:
                                del self.pending_rowspans[col_idx]
                elif tag in ("td", "th") and self.in_table:
                    self.in_cell = True
                    self.current_cell_parts = []
                    
                    # Skip columns that are covered by rowspan from previous rows
                    while self.current_col_index in self.pending_rowspans:
                        if self.pending_rowspans[self.current_col_index] > 0:
                            self.current_row.append("")  # Placeholder for rowspan continuation
                            self.pending_rowspans[self.current_col_index] -= 1
                            if self.pending_rowspans[self.current_col_index] == 0:
                                del self.pending_rowspans[self.current_col_index]
                        self.current_col_index += 1
                    
                    # Parse rowspan and colspan attributes
                    rowspan = 1
                    colspan = 1
                    for attr_name, attr_value in attrs:
                        if attr_name == "rowspan":
                            try:
                                rowspan = int(attr_value)
                            except (ValueError, TypeError):
                                pass
                        elif attr_name == "colspan":
                            try:
                                colspan = int(attr_value)
                            except (ValueError, TypeError):
                                pass
                    
                    # Store rowspan and colspan for use in handle_endtag
                    self.current_cell_rowspan = rowspan
                    self.current_cell_colspan = colspan
                    
                    # Record rowspan for future rows
                    if rowspan > 1:
                        for c in range(self.current_col_index, self.current_col_index + colspan):
                            if c not in self.pending_rowspans:
                                self.pending_rowspans[c] = rowspan - 1
                            else:
                                self.pending_rowspans[c] += rowspan - 1
                    
            def handle_endtag(self, tag):
                if tag == "table":
                    self.in_table = False
                elif tag == "tr" and self.in_table:
                    if self.current_row:
                        self.rows.append(self.current_row)
                    self.current_row = []
                elif tag in ("td", "th") and self.in_table:
                    self.in_cell = False
                    cell_text = "".join(self.current_cell_parts).strip()
                    # Add the cell text (only once, even if colspan > 1)
                    # SPAN command will handle the visual merging
                    self.current_row.append(cell_text)
                    self.current_cell_parts = []
                    # For colspan > 1, we need to add empty placeholders for the merged columns
                    # ReportLab Table requires all columns to be present in the data
                    # The SPAN command will merge them visually
                    colspan = getattr(self, 'current_cell_colspan', 1)
                    for _ in range(1, colspan):
                        self.current_row.append("")  # Empty placeholder for merged columns
                    # Advance column index by colspan (not just 1)
                    self.current_col_index += colspan
                    
            def handle_data(self, data):
                if self.in_cell:
                    self.current_cell_parts.append(data)
            
            def get_spans(self) -> List[Tuple[int, int, int, int]]:
                """Calculate span commands from the parsed table structure."""
                spans = []
                
                class SpanCalculator(HTMLParser):
                    def __init__(self, parent):
                        super().__init__()
                        self.parent = parent
                        self.row_idx = -1
                        self.col_idx = 0
                        self.pending_rowspans = {}
                        self.spans = []
                        
                    def handle_starttag(self, tag, attrs):
                        if tag == "tr":
                            self.row_idx += 1
                            self.col_idx = 0
                            # Handle pending rowspans
                            for c in sorted(self.pending_rowspans.keys()):
                                if self.pending_rowspans[c][1] > 0:  # rowspan > 0
                                    start_row, rs, cs = self.pending_rowspans[c]
                                    self.pending_rowspans[c] = (start_row, rs - 1, cs)
                                    if self.pending_rowspans[c][1] == 0:
                                        del self.pending_rowspans[c]
                        elif tag in ("td", "th"):
                            # Skip columns covered by rowspan
                            while self.col_idx in self.pending_rowspans:
                                if self.pending_rowspans[self.col_idx][1] > 0:
                                    self.pending_rowspans[self.col_idx] = (
                                        self.pending_rowspans[self.col_idx][0],
                                        self.pending_rowspans[self.col_idx][1] - 1,
                                        self.pending_rowspans[self.col_idx][2]
                                    )
                                    if self.pending_rowspans[self.col_idx][1] == 0:
                                        del self.pending_rowspans[self.col_idx]
                                self.col_idx += 1
                            
                            rowspan = 1
                            colspan = 1
                            for attr_name, attr_value in attrs:
                                if attr_name == "rowspan":
                                    try:
                                        rowspan = int(attr_value)
                                    except (ValueError, TypeError):
                                        pass
                                elif attr_name == "colspan":
                                    try:
                                        colspan = int(attr_value)
                                    except (ValueError, TypeError):
                                        pass
                            
                            if rowspan > 1 or colspan > 1:
                                # Record span: (row_start, col_start, row_end, col_end)
                                # Note: col_end and row_end are inclusive (the last cell in the span)
                                row_end = self.row_idx + rowspan - 1
                                col_end = self.col_idx + colspan - 1
                                self.spans.append((self.row_idx, self.col_idx, row_end, col_end))
                                
                                # Track rowspan for future rows
                                if rowspan > 1:
                                    for c in range(self.col_idx, self.col_idx + colspan):
                                        self.pending_rowspans[c] = (self.row_idx, rowspan - 1, colspan)
                            
                            self.col_idx += colspan
                
                calculator = SpanCalculator(None)
                try:
                    calculator.feed(html_str)
                except Exception as e:
                    if log_warning:
                        log_warning("Failed to calculate spans from HTML", e)
                    return []
                
                return calculator.spans
        
        parser = HTMLTableParser()
        try:
            parser.feed(html_str)
        except Exception as e:
            if log_warning:
                log_warning("Failed to parse HTML table", e)
            return [], []
        
        # Calculate spans by re-parsing
        spans = parser.get_spans()
        
        return parser.rows if parser.rows else [], spans
    
    @staticmethod
    def calculate_table_column_widths(
        rows: List[List[str]],
        total_width: float,
        font_size: float,
        font_name: str,
        canvas_obj=None
    ) -> List[float]:
        """
        Calculate column widths for a table based on content length.
        
        This distributes column widths proportionally based on the maximum content
        length in each column, rather than using equal widths.
        
        Args:
            rows: 2D list of table cell texts
            total_width: Total available width for the table
            font_size: Font size in points
            font_name: Font name
            canvas_obj: Optional canvas object for accurate text measurement
            
        Returns:
            List of column widths in points
        """
        if not rows or not rows[0]:
            return []
        
        num_cols = len(rows[0])
        if num_cols == 0:
            return []
        
        # Calculate maximum text width for each column
        try:
            from reportlab.pdfbase import pdfmetrics
        except ImportError:
            pdfmetrics = None
        
        max_col_widths = [0.0] * num_cols
        
        for row in rows:
            for col_idx, cell_text in enumerate(row):
                if col_idx >= num_cols:
                    continue
                if not cell_text:
                    continue
                
                # Measure text width
                if canvas_obj and pdfmetrics:
                    try:
                        canvas_obj.setFont(font_name, font_size)
                        text_width = pdfmetrics.stringWidth(cell_text, font_name, font_size)
                    except Exception:
                        # Fallback: approximate width
                        text_width = len(cell_text) * font_size * 0.6
                else:
                    # Fallback: approximate width
                    text_width = len(cell_text) * font_size * 0.6
                
                # Add some padding for cell padding
                cell_width = text_width + (font_size * 0.3)  # Add 30% of font size as padding
                max_col_widths[col_idx] = max(max_col_widths[col_idx], cell_width)
        
        # If all columns have zero width, use equal distribution
        total_max_width = sum(max_col_widths)
        if total_max_width == 0:
            return [total_width / num_cols] * num_cols
        
        # Distribute total_width proportionally based on max widths
        col_widths = []
        for max_w in max_col_widths:
            if total_max_width > 0:
                proportion = max_w / total_max_width
                col_width = total_width * proportion
            else:
                col_width = total_width / num_cols
            col_widths.append(max(col_width, total_width * 0.05))  # Minimum 5% of total width
        
        # Normalize to ensure sum equals total_width
        actual_total = sum(col_widths)
        if actual_total > 0:
            scale_factor = total_width / actual_total
            col_widths = [w * scale_factor for w in col_widths]
        
        return col_widths

